### ISSUE TITLE
DeflateFrameExtension could not be instantiated

### ISSUE THREAD

**Issue by RosenPIvanov** [LivePersonInc/dropwizard-websockets#16]
I tried to setup a project with drop-wizard 1.1.0 (also 1.1.2), but the server do no starts because of this error:
org.eclipse.jetty.websocket.api.extensions.Extension: Provider org.eclipse.jetty.websocket.common.extensions.compress.DeflateFrameExtension could not be instantiated

Can you provide some suggestion. I tried all the ways that was suggested in the documentation.

Thanks!

**Comment by RosenPIvanov** [comment]
I found a problem with the dependencies:  javax-websocket-server-impl needs to be version 9.4.

**Comment by aliakhtar** [comment]
I'm encountering the same issue. @RosenPIvanov What was the exact version you used?

**Comment by aliakhtar** [comment]
@eitan101 Can you help?

**Comment by aliakhtar** [comment]
If I use `<version>9.4.2.v20170220</version>` I get `java.lang.NoSuchMethodError: org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.getFactory()Lorg/eclipse/jetty/websocket/server/WebSocketServerFactory;`
