### ISSUE TITLE
Can't @Inject into websocket endpoint

### ISSUE THREAD

**Issue by mpbarnwell** [LivePersonInc/dropwizard-websockets#2]
I'm trying to figure out the best way of accessing singleton services in from a websocket endpoint class without resorting to static fields/methods. I was expecting to be able to use @Inject since it's managed by jersey but it's not working.

I've thrown together an example project using @Inject on both a regular Dropwizard resource and a websocket endpoint, see https://github.com/mpbarnwell/dropwizard-websockets-test 

As expected, using curl against the Dropwizard resource returns the service's hash code:

```
curl -X GET http://localhost:8080/test
1979257230
```

But running against the webservice endpoint produces a NPE.

```
curl 'http://localhost:8080/ws' -H 'Sec-WebSocket-Version: 13' -H 'Sec-WebSocket-Key: Yx2RoE1qwByK+r3fO25+/Q==' -H 'Upgrade: websocket' -H 'Connection: Upgrade'
��NullPointerException
```

**Comment by mpbarnwell** [comment]
I spent a little more time on this, this would achieve the result I'm expecting, of course the environment isn't available during initialization, so it doesn't actually work. 

``` java
        websocket.addEndpoint(ServerEndpointConfig.Builder.create(DeviceRegistrationHandler.class, "/device").configurator(new BasicServerEndpointConfigurator() {
            @Override
            public <T> T getEndpointInstance(Class<T> clazz)
                    throws InstantiationException {
                ServiceLocator sl = ((ServletContainer) environment.getJerseyServletContainer()).getApplicationHandler().getServiceLocator();
                return sl.createAndInitialize(clazz);
            }
        }).build());
```

It looks like this is a wider symptom of JSR-356, even Spring has to use a static method to lookup the context, https://github.com/spring-projects/spring-framework/blob/master/spring-websocket/src/main/java/org/springframework/web/socket/server/standard/SpringConfigurator.java

Probably best to close this issue but I would appreciate any other suggestions on how to 'wire up' endpoints with services.

**Comment by tsarna** [comment]
I had to use requestStaticInitialization on my websocket class. It would be nice if there was a solution to this. It would probably require addressing #3 first.

**Comment by eitan101** [comment]
unfortanatly the ServerEndpointConfig interface should be able to return [its endpointClass](https://docs.oracle.com/javaee/7/api/javax/websocket/server/ServerEndpointConfig.html#getEndpointClass--), so you can't avoid static class for websocket server using jsr356.
