### ISSUE TITLE
Allow endpoints to be registered during run()

### ISSUE THREAD

**Issue by tsarna** [LivePersonInc/dropwizard-websockets#3]
It would be nice if the endpoint classes could be registered in the application run() method, instead of having to be provided during initialize().

Among other advantages, this would allow them to be optional based on the configuration.

**Comment by eitan101** [comment]
I intentionally tried to avoid this option in order to follow the way other bundles work, for example [assets-bundle](http://www.dropwizard.io/0.9.2/docs/manual/core.html#serving-assets).

**Comment by bucht** [comment]
Changing this would make it a lot easier to get dropwizard's configuration into the endpoint to set properties on the session for example.

**Comment by eitan101** [comment]
I added option to addEndpoint to the bundle from the run method. You can see it [here](https://github.com/LivePersonInc/dropwizard-websockets/blob/3d0f5ac64908f73cbcb4d74b3c6dd82f358b6874/src/test/java/io/dropwizard/websockets/MyApp.java#L91).
