### ISSUE TITLE
Pointers needed on how to configure security for websocket endpoints.

### ISSUE THREAD

**Issue by tsarna** [LivePersonInc/dropwizard-websockets#4]
Even after quite a bit of searching, it's not at all clear to me how one could hook in authentication based on the original HTTP request (eg, based on session or headers).

**Comment by eitan101** [comment]
I can share with you our experience for authentication on web-sockets.
- You can register authentication filter that will stop the first get request. Cons: (1) the browser clients will not have notion why the open websocket request was refused. (2) The authentication is done only on connection establishment.
- You can fail the upgrade request by falling the handshake. Cons: Same as above and more.
- You can write your call authentication layer on your onOpen. Expiration of the authentication can be done by calling this layer also onMsg and when you use session.send. Cons: you have to take care of authentication by your own. Enjoy. And another thing, browser clients cannot send headers on the upgrade request so you can use either URL params or in-session message to pass the credentials. Sorry.

We chose the third approach, tell me if you think we can do better.
