### ISSUE TITLE
Update out of date dependencies?

### ISSUE THREAD

**Issue by aliakhtar** [LivePersonInc/dropwizard-websockets#5]
Heya,

Great project, and I'd love to use it. But VersionEye shows that a lot of dependencies are out of date, and one includes a security vulnerability: https://www.versioneye.com/user/projects/5642ede8c5999a0009027e23

Would it be possible to update the project to latest versions & push it to maven? Should be a simple change, and then I'd love to use this.

Thanks.

**Comment by eitan101** [comment]
It is up-to-date with dropwizard release. The outdated dependencies are inherited from there.
