### ISSUE TITLE
DropWizard 1.0 compatibility

### ISSUE THREAD

**Issue by kebernet** [LivePersonInc/dropwizard-websockets#7]
Are there any plans to upgrade this to be compatible with the 1.0.0 build of dropwizard?

**Comment by darrenhaken** [comment]
Any update on this?

**Comment by kebernet** [comment]
@darrenhaken That PR got merged. There is a 1.0.0-1 version that includes the change.

**Comment by darrenhaken** [comment]
@kebernet oh ok great. I was using 1.0.0-SNAPSHOT and I just upgraded to the latest but wiring in the Bundle no longer seems to work. I'd assumed it was because I'm using 1.x of Dropwizard.

Here is how I wire up the socket:

```
bootstrap.addBundle(
            new WebsocketBundle(
                // An endpoint configurator to allow the websocket services to be configured by Guice.
                new ServerEndpointConfig.Configurator() {
                    @Override
                    public <T> T getEndpointInstance(Class<T> endpointClass) throws InstantiationException {
                        return GuiceInjectorAccess.INJECTOR.getInstance(endpointClass);
                    }
                },
                SessionEndpoint.class)
        );
```

Any ideas?

**Comment by kebernet** [comment]
Yeah, the "latest" version is likely going to show as 1.2.0, but that is not the one that got published. That built is still tied to DW 0.9.4 IIRC.

**Comment by darrenhaken** [comment]
Ah so 1.2 will be incompatible.

Would it be possible to release a 2.x version of the library which is considered compatible with DW 1.x? That would follow semantic versioning as it's a breaking change http://semver.org/

**Comment by eitan101** [comment]
Sorry for the late response. 1.2 was released by mistake. The demands for DW plugins version names is to start with the version of DW, when DW will have 1.2 or higher it will be possible.
